test: add e2e tests (#504)
* feat: move from fake ip vars to test types vars

* feat: add mock e2e scripts

* feat: add mocha setup

* feat: run probe container from e2e setup

* ci: trigger e2e

* feat: wait until probe connects

* feat: add failing usage of matchApiSchema

* fix: matchApiSchema method

* fix: mocha throwing ERROR: null in case of ts compilation error

* feat: add util parser

* feat: change runner

* feat: use got response in mocha plugin

* test: add measurement e2e tests

* feat: add e2e wallaby configuration

* feat: move e2e .mocharc

* feat: add e2e folder to tsconfig

* feat: add e2e cases for all measurement types

* fix: http schema

* refactor: move files

* feat: add locations e2e

* fix: add missing nulls to schema

* test: add offline probes tests

* test: add adopted probes tests e2e

* fix: e2e mocharc

* fix: tests order

* feat: run api as docker container

* fix: run api on port 3000

* fix: local run

* refactor: docker manager

* fix: e2e wallaby

* fix: schema hostname format

* fix: remove unused env var

* fix: add missing awaits

* fix: remove manual json.parse

* fix: log measurement status

* feat: disable rtt null

* fix: add wait for disconnect

* ci: trigger

* fix: retrun rtt null back

* refactor: move e2e to test folder

* fix: use db urls from config

* fix: build probe image from github master

* fix: get rtt schema back